# Default configuration template for WinOpsTool
# Copy this file and modify according to your needs

environment_variables:
  system: {}
  user: {}

registry: []

users:
  create: []
  groups: []

services: []

firewall:
  inbound: []
  outbound: []

software:
  install: []
  uninstall: []

permissions: []

applications:
  startup: []
  processes:
    start: []
    stop: []
