# Default configuration template for Windows System Management Tool
# Copy this file and modify according to your needs

environment_variables:
  system:
    # Example: PATH: "%PATH%;C:\NewPath"
  user:
    # Example: TEMP: "C:\Users\Username\AppData\Local\Temp"

registry:
  # Example:
  # - path: "HKLM\Software\MyApp"
  #   name: "Version"
  #   type: "REG_SZ"
  #   value: "1.0.0"

users:
  # Example:
  # - username: "newuser"
  #   password: "password123"
  #   groups: ["Users", "Power Users"]
  #   comment: "New user account"

services:
  # Example:
  # - name: "MyService"
  #   start_type: "auto"
  #   state: "running"
  #   description: "My custom service"

firewall:
  # Example:
  # - name: "Allow Web Traffic"
  #   direction: "in"
  #   action: "allow"
  #   protocol: "TCP"
  #   local_port: "80,443"
  #   enabled: true

software:
  install:
    # Example:
    # - path: "C:\Installers\app.msi"
    #   arguments: "/quiet"
    #   verify_path: "C:\Program Files\App\app.exe"
  uninstall:
    # Example:
    # - name: "App to Remove"

permissions:
  # Example:
  # - path: "C:\Data"
  #   permissions:
  #     - user: "Users"
  #       rights: ["read", "execute"]
  #       type: "allow"

applications:
  startup:
    # Example:
    # - name: "My App"
    #   command: "C:\Apps\myapp.exe"
    #   enabled: true
  processes:
    # Example:
    start:
      # - path: "C:\Apps\service.exe"
      #   arguments: "--daemon"
    stop:
      # - "unwanted_process.exe"
